### ISSUE TITLE
Hello, I would appreciate it if you could give me some advice for beginners.

### ISSUE THREAD

**Issue by ghost** [albatror/AL-Offsets-Dumper#1]
I saw your adkv post but I'm still having trouble using it.
First of all, the first question is, can you explain in detail how to obfuscate client.exe?
I tried to solve the problem on my own, but my poor language skills and Googling skills are not enough to learn it.
I don't want to take up your time, but I would appreciate it if you could take the time to help.

discord : kakao112

**Comment by albatror** [comment]
you can use THEMIDA(64) or VMprotect for example or any soft like this to obfuscate files
